sudo: required
services:
    - docker

before_install:
    - docker build -t vishalg92/docker-react -f Dockerfile.dev .
    
script:
    - docker run vishalg92/docker-react npm run test -- --coverage
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-934088575863"
    bucket_path: "docker-react"
    on:
        branch: master
    